name: Deploy to DigitalOcean

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H talibg.com >> ~/.ssh/known_hosts

            - name: Sync files via rsync
              run: |
                  rsync -avz --delete index.html styles.css root@talibg.com:/var/www/talibg.com/
