name: Deploy to DigitalOcean

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install SSH key
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.DEPLOY_KEY }}

            - name: Add known hosts
              run: ssh-keyscan -H 46.101.28.106 >> ~/.ssh/known_hosts

            - name: Deploy files with rsync
              run: rsync -avz --delete ./ root@46.101.28.106:/var/www/talibg.com/
